#!/usr/bin/env bash
# Script to install nginx and configure a custom 404 page with the string "Ceci n'est pas une page"

# Update and install nginx
apt-get update -y
apt-get install nginx -y

echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

sed -i '/server_name _;/a \ \terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

service nginx reload
