#!/usr/bin/env bash
# Configure UFW to allow only ports 22, 80, and 443 on web-01

# Install UFW
sudo apt-get update
sudo apt-get install ufw -y

# Allow essential ports
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Set default policy to deny all other incoming traffic
sudo ufw default deny incoming

# Enable the firewall
sudo ufw --force enable
